apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  test.server: |
    microsoft.com:53 {
        errors
        cache 30
        rewrite name substring microsoft.com bar.svc.cluster.local
        forward . 10.0.0.10 # # you can redirect this to a specific DNS server such as 10.1.0.20
    }
